### ISSUE TITLE
_.extend is depricated

### ISSUE THREAD

**Issue by gabrielwelsche** [scottwrobinson/camo#1]
Hi Scott!

some lodash methods are depricated, e.g. you used _.extends in base-document.js 
see https://github.com/lodash/lodash/wiki/Roadmap

"Remove aliases all, any, backflow, collect, compose, contains, detect, extend, fold, foldr, head, include, inject, iteratee, methods, object, select, tail, & unique"

kind regards
gabriel

**Comment by scottwrobinson** [comment]
Thanks, Gabriel!
