### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by periabyte** [scottwrobinson/camo#114]
Hi @scottwrobinson,

[Hacktoberfest](https://hacktoberfest.digitalocean.com) is up for the whole october, consider labeling some open issues with hacktoberfest might help fix them, or you might even find a new maintainer for this project. This project is awesome please, I hope you find someone to help maintain this project.

**Comment by scottwrobinson** [comment]
Hi @periabyte,

Thanks for bringing this up! That's a great idea. I will see if I can get organized over the weekend and submit some issues.

I've actually been actively trying to find someone to help maintain the project. It's more difficult than it sounds 😉 . If you know of anyone or have any ideas, please do let me know.

Also, glad to hear you like the project. Always nice to know it's helping people!
