### ISSUE TITLE
static collectionName improvement

### ISSUE THREAD

**Issue by resistdesign** [scottwrobinson/camo#16]
You asked how to do this better here: https://github.com/scottwrobinson/camo/blob/master/lib/document.js#L41

Just use a static property `static collectionName = 'people';` instead of using `super('people')`.

Then your `Document` class can do `this.constructor.collectionName` to access it.

http://jsfiddle.net/resistdesign/wgsh2sex/

**Comment by scottwrobinson** [comment]
Thanks for the suggestion, Ryan! Unfortunately static properties aren't available in Node right now, and as much as I'd like to use Babel I don't think it would be reasonable to require the user to do so also.

Instead I've been thinking we should just do something like this:

```javascript
'use strict';

class Document {
  constructor() {

  }
  
  static collectionName() {
    return this.name.toLowerCase();
  }
}

class Person extends Document {
  constructor() {
    super();
  }

  static collectionName() {
    return 'people';
  }
}

class Bill extends Person {
  constructor() {
    super();
  }
}

console.log('Document:', Document.collectionName());  // Prints 'document'
console.log('Person:', Person.collectionName());      // Prints 'people'
console.log('Bill:', Bill.collectionName());          // Prints 'people'
```

Requiring the user to add the `collectionName()` function isn't as good as using a property, but it's better than what we're doing now. Also, if `collectionName()` isn't provided we just use the class name by default (and optionally with [Pluralize](https://github.com/blakeembrey/pluralize) to make it look nicer).

Thoughts?

Thanks for the suggestion!

**Comment by resistdesign** [comment]
Honestly, short of static props, that's a really nice solution and I'd be happy to use it :)
