### ISSUE TITLE
Saving Document Reference

### ISSUE THREAD

**Issue by b22n** [scottwrobinson/camo#23]
```
Doc1 extends Document {
...
}
Doc2 extends Document {
  constructor(){
    this.ref = {
      type: Doc1
    }
  }
}

Doc2.create({
   ref: "valid ObjectId string" 
})
```

In this case, It passes the validation, but reference id is saved as String not a ObjectId.

**Comment by scottwrobinson** [comment]
I'm assuming you're using Mongo, and not NeDB, correct? If you're using Mongo then try creating/assigning an `ObjectId` and not a string, like this:

```javascript
var ObjectId = require('mongodb').ObjectId;

Doc2.create({
    ref: new ObjectId("valid ObjectId string");
});
```

I believe that should work. If not, I'll look in to it further.

Hope this helps!
