### ISSUE TITLE
`that.collectionName is not a function` on EmbeddedDocument

### ISSUE THREAD

**Issue by ijsf** [scottwrobinson/camo#26]
I am having an issue when trying to create (and save) an `EmbeddedDocument`. I have the following class:

    class Reminder extends camo.EmbeddedDocument
    {
      constructor()
      {
        super();
        this.enabled = { type: Boolean, required: true };
      }
    }

Now, when I create a `Reminder` instance that does not adhere to the above, e.g. the `enabled` property is missing, like in this example:

    Reminder.create({}).save();

I get the following error:

    info: TypeError: that.collectionName is not a function

This is obviously an artifact of the new `collectionName` functionality in the `validate` function inside camo. Except, `collectionName` does not exist in `EmbeddedDocument` instances.

Probably quite an easy fix.

**Comment by scottwrobinson** [comment]
Yup, you're right. Dumb mistake, but an easy fix.

Also, just to be clear, make sure you're calling `save()` on the `Document` and not `EmbeddedDocument` object.

Should have the fix out later tonight with the rest of the bugs I'm working on. Thanks for pointing this out!

**Comment by CKarper** [comment]
+1
