### ISSUE TITLE
How do you properly close a connection?  How do you handle connection/socket errors?

### ISSUE THREAD

**Issue by niftylettuce** [scottwrobinson/camo#33]
How are these errors handled?  I'm coming from Mongoose

**Comment by michaeljota** [comment]
You can search in closed issues. He make this with Promises. Short answer: Just catch the error, like a Promise. (.then().catch();)

**Comment by niftylettuce** [comment]
@michaeljota so a typical app might look like:

```js
 
```

**Comment by niftylettuce** [comment]
@michaeljota how can we `await` a db connection before starting our app?

**Comment by niftylettuce** [comment]
https://github.com/scottwrobinson/camo/issues/17#issue-120250106

**Comment by michaeljota** [comment]
IDK. But, I see something like like that as a title of some close issue.

[ref #30](https://github.com/scottwrobinson/camo/issues/30)

**Comment by niftylettuce** [comment]
Here's how I did it (I'm using Koa):

```js
 // connect to the db
connect(config.db).then(db => {
  console.log(`MongoDB connected to ${config.db}`);
}).catch(err => {
  console.error(err);
  process.exit(1);
});

// initialize the app
const app = new Koa();
```
