### ISSUE TITLE
How to use 'match' properly?

### ISSUE THREAD

**Issue by michaeljota** [scottwrobinson/camo#42]
I trying to use 'match', but as #41 it throws not a function.

Here is my schema:

```javascript
class User extends Document {
    constructor(){
        super();
        //Just the part where using the match. 
        this.email = {
            type: String,
            match: '/.+\@.+\..+/'
        }
}
```

**Comment by scottwrobinson** [comment]
You should specify a regex in `match`. So you're example would be:

```javascript
class User extends Document {
    constructor(){
        super();
        //Just the part where using the match. 
        this.email = {
            type: String,
            match: /.+\@.+\..+/
        }
}
```

Although it probably wouldn't hurt to allow plain regex strings as well (like you're using).

Just remove the single quotes (`'`). Here is a quick [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) example:

```javascript
var emailRegex = /.+\@.+\..+/;
emailRegex.test('john@example.com');    // true
emailRegex.test('example.com');    // false
```

Unless you have any other follow-up questions, I'm going to close the issue. Thanks!

**Comment by michaeljota** [comment]
Thanks. :+1:
