### ISSUE TITLE
Neither 'PostValidate' or 'PreSave' hooks are not altering the document.

### ISSUE THREAD

**Issue by michaeljota** [scottwrobinson/camo#43]
I don't know if i'm doing this properly, but I'm trying to hash the password in either 'PreSave' or 'PostValidate' (I supposse PostValidate get's calling just before PreSave).

PostValidate got called, I think PreSave is not. But in either case, I doesn't make permanent changes to the document. The changes that are made, are lost when they get save.

``` javascript
    postValidate () {
        if(this.password) {
            console.log('Salting');
            this.salt = new Buffer (crypto.randomBytes(16).toString('base64'), 'base64');
            console.log(this.salt);
            this.password = this.hashPassword(this.password);
        }
        this.updated = Date.now();
    }

    postSave () {
        console.log('Post save');
        console.log(this);
    }
```

The console outputs show they are being called. PostSave show changes in the document, but it the datastorage (I'm using NeDB) there is not salt in the document, and the password it's not hashed.

Any thoughs?

Thanks for camo. I don't think I ever got to post so much in a issue list, that is not mine own.

PS: I'm trying to using this with Passport, but all the examples are with 'mongoose'. I'm trying to write all the examples to camo, but I've fail, so far. Have you use Camo with Passport? How did you?

**Comment by vfreitas-** [comment]
+1 Same here, I'm trying to set a property value in the preSave hook, but the changes are being lost.

```
preSave() {
	this.slug = slugify(this.title); //this.title = 'some phrase'
	console.log(this.slug); // 'some-phrase'
        //mongodb = null
}
```

**Comment by michaeljota** [comment]
He is unable to work on it right now. But as soon as he can, he will look at it.

I just created a function to hash the password and called before the saving. It might work (It should at least, I hadn't try it).

It might work for you as well. :D

**Comment by michaeljota** [comment]
Update: It works!. Just use the function that make changes in the object and called before salving. :D

**Comment by michaeljota** [comment]
Update2: I use password get a setter to hash the password.

```javascript
    set password (password) {
        this._password = password;
        this.salt = this.makeSalt();
        this.hashedPassword = this.encryptPassword(password);
    }
    
    get password () {
        return this._password;
    }
```

That solve my problem too, and it's easies to use, 'cause I just create the document with the 'password' param, and it actually hash the password, resulting:

```json
{"name":"Test User","email":"test@test.com","hashedPassword":"(hashedPassword)","role":"user","provider":"local","salt":"(salt)","_id":"KNW4kT5nqj5cTg4V"}
```

**Comment by fxpoet** [comment]
+1 same issue.but I solved.
add single line code at line 138, node_modules/camo/lib/document.js 

data = that._toData({_id:false});

**Comment by kurdin** [comment]
>data = that._toData({_id:false});
can you add this please and release new version?

**Comment by caseyWebb** [comment]
PRs! PRs for everyone!
