### ISSUE TITLE
wrong return value from BaseDocument#_getHookPromises (array of arrays of promise instead of array of promise)

### ISSUE THREAD

**Issue by royaltm** [scottwrobinson/camo#57]
Long story short: this really ruined my night: https://github.com/scottwrobinson/camo/blob/b2bd9846234a1fe969e4f8385cdcf7ba66fffc5a/lib/base-document.js#L541

The typeless at its worst...

this will push an array with (a possible) promise into an array
```
hookPromises.push(_.invoke([this], hookName));
```
resulting in `[[promise]]` instead of `[promise]`

and this is bad, because
`Promise.all([[promise]])` immediately succeeds.

So any error in ANY of this document hook's promise will be (possible silently) discarded!

why just not

```
hookPromises.push(this[hookName]());
```

or at least:

```
hookPromises = hookPromises.concat(_.invoke([this], hookName));
```

**Comment by scottwrobinson** [comment]
Thanks for bringing this up. I should be able to try out your fix tomorrow.

Thanks!

**Comment by scottwrobinson** [comment]
Also, if you can post any code that shows the error that would be great. Thanks!

**Comment by royaltm** [comment]
here you [go](https://gist.github.com/royaltm/36ed4640ab3251bcc74b)
