### ISSUE TITLE
Can it sync with remote?

### ISSUE THREAD

**Issue by katopz** [scottwrobinson/camo#61]
Let say I use `NeDB` when offline and sync to remote `MongoDB` when online similar to [this](http://lowla.github.io/lowladb-json-database/browser.html#Syncing) and may I ask for example if it poossible? (BTW `offline capability` should add to features in readme if it possible tho)

Thanks

**Comment by scottwrobinson** [comment]
There aren't any native sync capabilities like the one you referenced. You'd have to write the syncing code yourself. I think this is a bit out of scope for an ODM like Camo. I think it would make more sense for syncing to be implemented in the DB or application layer, depending on your needs.

If the underlying DB driver supports syncing (which I don't think either of them do) then you can access the driver using `camo.getClient().driver()`.

**Comment by dalcib** [comment]
It would be nice to have a driver do [marsdb](https://github.com/c58/marsdb).

**Comment by scottwrobinson** [comment]
@dalcib from quick glance it looks like that would be possible. If you want to discuss more please open a separate issue. Thanks for the suggestion!

**Comment by scottwrobinson** [comment]
The sync feature seems to be out of scope for Camo, so I'm closing this issue.
