### ISSUE TITLE
nedb cross table support

### ISSUE THREAD

**Issue by cdaringe** [scottwrobinson/camo#68]
hello:

from the docs it's reported that camo supports nedb.  i can do a test, but figured id ask first. because `nedb` is just a single store, how does camo handle cross model relationships if those relationships span multiple stores?

**Comment by scottwrobinson** [comment]
Camo creates a new NeDB `Datastore` for each table you create. If you're storing the data in files (as opposed to memory), then there will be a separate file for each table. Camo then handles the relationships of objects between these files.

Let me know if you have any other questions. Thanks!

**Comment by cdaringe** [comment]
awesome! that's what i was hoping for :)
