### ISSUE TITLE
loadOneOrCreate()

### ISSUE THREAD

**Issue by WorldMaker** [scottwrobinson/camo#7]
This would be a useful convenience method to have. The big place I could use this is authentication code where the usernames are coming from an external source and I want to create a blank user record for a new to my app username.

Because of the importance of such a user lookup, it would be best if can attempt to be atomic in the database. Current version of my code is using the mixin `mongoose-findorcreate` for mongoose, and this convenience method would be another push over the hump of switching away from mongoose.

It's possible you might want to use an option on `loadOne(...)` instead of an entirely new method `loadOneOrCreate(...)`, such as `loadOne(..., { create: true })`. For my use case I don't particularly need to know if this one was created for the first time or not, but that may be something that others are interested in and returning that information might be reason to use a separate method instead of sharing one. Your call.

Thanks.

**Comment by scottwrobinson** [comment]
So it looks like the [atomicity is possible](http://stackoverflow.com/questions/16358857/mongodb-atomic-findorcreate-findone-insert-if-nonexistent-but-do-not-update) with MongoDB 2.4, so my only issue is how this would work with other backends (NeDB, Taffy, etc). I'm hesitant to add a call to Camo that wouldn't be supported by the other backends, which makes me lean towards making it an option in `loadOne()`. But then, like you mentioned, we may need to let the caller know if the document was just created. Hmm....

Maybe we'll just have to add the `loadOneOrCreate()` method to Camo and use a non-atomic operation in NeDB, Taffy, etc.

I might test some things out and think about this. Any other thoughts or suggestions are welcome.

**Comment by scottwrobinson** [comment]
So I'm thinking the Camo API should more closely follow the Mongo API as that will be the most-used backend DB. Any other supported DBs will have to support the same Mongo functionality through the Camo interface client.

So, I'll be adding a `loadOneAndUpdate()` method, which can then be used for `loadOneOrCreate()` functionality. Still debating whether I should stick with `load..()` vs `find...()` though...

I should be able to get around to adding this within the next day or two.

**Comment by scottwrobinson** [comment]
Okay, I added support for this via `loadOneAndUpdate()`. Just use the option `{upsert: true}` and it'll return a newly saved document if one didn't exist already. Let me know if you have any questions.
