### ISSUE TITLE
Values for null items

### ISSUE THREAD

**Issue by paullryan** [scottwrobinson/camo#9]
Values for non-required null items should be left undefined when populating the database. This is a feature of document databases that keeps the column width from blowing out the data store for wide sparse documents. Any chance you can update this? I'm not quite sure where to look for that final set from Schema to key-value pair.

**Comment by scottwrobinson** [comment]
Ok, just pushed a fix for this. Items that are null should still be set in the DB since Mongo supports null, but if the item is undefined then it is left as undefined and not set.

Please let me know if you run in to any problems.

Thanks for submitting the issue!
