### ISSUE TITLE
Connect to mongo using certificate

### ISSUE THREAD

**Issue by duartealexf** [scottwrobinson/camo#92]
I looked around for it, but I'm guessing there is no support for connecting to mongo using ssl certificate? For example, on command line I connect to mongo using:

`mongo --port=27017 --ssl  --sslCAFile /var/lib/mongo/ca/mongo-ca.crt   --sslPEMKeyFile /var/lib/mongo/ca/localhost.pem   --sslAllowInvalidHostnames   -u root -p XXXX admin`

Is there any support for it?

**Comment by scottwrobinson** [comment]
Sorry for the late reply.

Can you achieve the same thing using a Mongo connection string (`mongodb://username:pw@localhost/people`)? Camo also [exposes the underlying driver](https://github.com/scottwrobinson/camo#misc), which in the case of Mongo would be the `MongoClient`. This may be what you need.

**Comment by duartealexf** [comment]
No problems. I will try that. Thanks!
