### ISSUE TITLE
[Question] Can you model relationships using Camo?

### ISSUE THREAD

**Issue by TheHandsomeCoder** [scottwrobinson/camo#94]
For example you could have a Type `Team` which could have an array property of Type `Player`

I've looked through the docs and through some examples, but I haven't been able to find an answer

**Comment by scottwrobinson** [comment]
Hi there! Yep, you can do this. Unfortunately the README doesn't show off all of Camo's features. There are some [great examples](https://github.com/scottwrobinson/camo/blob/master/test/document.test.js) in some of the tests though.

[Here](https://github.com/scottwrobinson/camo/blob/master/test/document.test.js#L123) is one specific example.

Let me know if you have any other questions or if we can close the issue. Thanks!

**Comment by TheHandsomeCoder** [comment]
Yup this is exactly what I was looking for :) cheers
