### ISSUE TITLE
Gridfs support?

### ISSUE THREAD

**Issue by pyros2097** [scottwrobinson/camo#95]
Any plans to support grid fs?

**Comment by scottwrobinson** [comment]
I don't have any plans to support grid fs at this time, but I'm willing to hear ideas if you have any.

**Comment by pyros2097** [comment]
Well I guess its ok not to have support for it as I read in the mongodb docs that storing files less the 16MB in size is  better stored as a buffer and gridfs is only good for very large files that next seek capabilities like videos.

**Comment by scottwrobinson** [comment]
Thanks for bringing this up as it could be worth looking in to for the future. Let me know if you need anything else. Closing the issue for now.
